openapi: 3.0.0
info:
  description: The Apikey service is reserved for the administrator, it allows to manage the API keys
  version: 1.0.0
  title: Apikey service
  contact:
    email: ezteam@couperin.org
    name: ezTeam
  license:
    name: CeCILL 2.1
    url: http://www.cecill.info/licences/Licence_CeCILL_V2.1-en.html
servers:
  - url: https://unpaywall.inist.fr/api
tags:
  - name: apikey
  - name: ping
paths:
  /apikey:
    get:
      tags:
        - ping
      summary: Name of service
      operationId: get-apikey
      description: Name of service
      parameters: []
      responses:
        '200':
          description: OK
          content:
            Success:
              examples:
                response:
                  value: apikey service
              schema:
                type: string
                x-examples:
                  example-1: apikey service
  /apikey/ping:
    get:
      tags:
        - ping
      summary: Ping apikey service
      operationId: get-apikey-ping
      description: Ping apikey service
      responses:
        '204':
          description: No Content
      
  /apikey/health:
    get:
      tags:
          - ping
      summary: Health
      operationId: get-apikey-health
      description: Health on all service connected to apikey service
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                Success:
                  value:
                    redis:
                      elapsedTime: 0
                      status: true
                    elapsedTime: 0
                    status: true
                Error redis:
                  value:
                    redis:
                      elapsedTime: 3000
                      status: false
                      error: time out
                    elapsedTime: 3001
                    status: false
              schema:
                type: object
                properties:
                  redis:
                    type: object
                    properties:
                      elapsedTime:
                        type: integer
                      status:
                        type: boolean
                  elapsedTime:
                    type: integer
                  status:
                    type: boolean
                x-examples:
                  Example 1:
                    redis:
                      elapsedTime: 0
                      status: true
                    elapsedTime: 0
                    status: true
      
  /apikey/health/redis:
    get:
      summary: Health on redis service
      operationId: get-apikey-health-redis
      description: Health on redis
      tags:
        - ping
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Health'
    parameters: []
  /apikey/keys/${apikey}:
    get:
      tags:
        - apikey
      summary: Get config of apikey
      operationId: get-apikey-keys-$-apikey
      description: Get config of apikey
      parameters:
        - in: path
          name: apikey
          description: apikey
          required: true
          schema:
            type: string
      responses:
        '200':
          description: config of apikey
          content:
            application/json:
              schema:
                type: object
                properties:
                  apikey:
                    type: string
                    default: azerty
                  name:
                    type: string
                    default: john doe
                  attributes:
                    type: array
                    items:
                      type: string
                      default: '*'
                  access:
                    type: array
                    items:
                      type: string
                      default: graphql
                  allowed:
                    type: boolean
    put:
      tags:
        - apikey
      summary: Update apikey
      operationId: put-apikeys-keys-$-apikey
      description: Update apikey
      security:
        - x-api-key: []
      parameters:
        - in: path
          name: apikey
          description: apikey
          required: true
          schema:
            type: string
      responses:
        '200':
          description: update apikey
          content:
            application/json:
              schema:
                type: object
                properties:
                  apikey:
                    type: string
                    default: azerty
                  name:
                    type: string
                    default: john doe
                  attributes:
                    type: array
                    items:
                      type: string
                      default: '*'
                  access:
                    type: array
                    items:
                      type: string
                      default: graphql
                  allowed:
                    type: boolean
              examples:
                John Doe apikey:
                  value:
                    apikey: azerty
                    name: john doe
                    attributes:
                      - '*'
                    access:
                      - graphql
                    allowed: true
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                x-examples:
                  example-1:
                    message: '"name" is required'
              examples:
                Name is required:
                  value:
                    message: '"name" is required'
        '401':
          $ref: '#/components/responses/Not-authorized'
    delete:
      tags:
        - apikey
      summary: Delete apikey
      operationId: delete-apikey-keys-$-apikey
      description: Delete apikey
      security:
        - x-api-key: []
      parameters:
        - in: path
          name: apikey
          description: apikey
          required: true
          schema:
            type: string
      responses:
        '204':
          description: apikey deleted
        '401':
          $ref: '#/components/responses/Not-authorized'
  /apikey/keys:
    get:
      tags:
        - apikey
      summary: Get all config of all apikey
      operationId: get-apikey-keys
      description: Get all config of all apikey
      security:
        - x-api-key: []
      responses:
        '200':
          description: update apikey
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    apikey:
                      type: string
                      default: azerty
                    name:
                      type: string
                      default: john doe
                    attributes:
                      type: array
                      items:
                        type: string
                        default: '*'
                    access:
                      type: array
                      items:
                        type: string
                        default: graphql
                    allowed:
                      type: boolean
              examples:
                John doe apikey:
                  value:
                    - apikey: azerty
                      name: john doe
                      attributes:
                        - '*'
                      access:
                        - graphql
                      allowed: true
            apikey of John Doe:
              examples:
                response:
                  value:
                    - apikey: azerty123456
                      name: John Doe
                      attributes:
                        - '*'
                      access:
                        - graphql
                      allowed: true
        '401':
          $ref: '#/components/responses/Not-authorized'
    delete:
      tags:
        - apikey
      summary: Delete all apikey
      operationId: delete-apikey-keys
      description: Delete all apikey
      security:
        - x-api-key: []
      responses:
        '204':
          description: all apikey are deleted
        '401':
          $ref: '#/components/responses/Not-authorized'
    post:
      tags:
        - apikey
      summary: Create apikey
      operationId: post-apikey-keys
      description: Create new apikey
      security:
        - x-api-key: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                attributes:
                  type: array
                  items:
                    type: string
                access:
                  type: array
                  items:
                    type: string
                allowed:
                  type: boolean
        description: config for apikey
        required: true
      responses:
        '200':
          description: update apikey
          content:
            application/json:
              schema:
                type: object
                properties:
                  apikey:
                    type: string
                    default: azerty
                  name:
                    type: string
                    default: john doe
                  attributes:
                    type: array
                    items:
                      type: string
                      default: '*'
                  access:
                    type: array
                    items:
                      type: string
                      default: graphql
                  allowed:
                    type: boolean
        '401':
          $ref: '#/components/responses/Not-authorized'
  /apikey/keys/load:
    post:
      tags:
        - apikey
      summary: Load apikey
      operationId: post-apikeys-keys-load
      description: Load apikey
      security:
        - x-api-key: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  apikey:
                    type: string
                  name:
                    type: string
                  attributes:
                    type: array
                    items:
                      type: string
                  access:
                    type: array
                    items:
                      type: string
                  allowed:
                    type: boolean
              x-examples:
                example-1:
                  - apikey: string
                    name: string
                    attributes:
                      - string
                    access:
                      - string
                    allowed: true
            examples:
              example-1:
                value:
                  - apikey: string
                    name: string
                    attributes:
                      - string
                    access:
                      - string
                    allowed: true
        description: apikeys
        required: true
      responses:
        '204':
          description: all apikey are loaded
        '401':
          $ref: '#/components/responses/Not-authorized'
components:
  responses:
    Not-authorized:
      description: Not authorized
      headers:
        x-api-key:
          schema:
            type: string
          description: redis password
      content:
        application/json:
          examples:
            response:
              value:
                message: Not authorized
      
    Health:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              status:
                type: boolean
              elapsedTime:
                type: integer
            x-examples:
              Example 1:
                name: redis
                status: true
                elapsedTime: 1
          examples:
            Success:
              value:
                name: name of service
                status: true
                elapsedTime: 1
            Error redis:
              value:
                name: redis
                elapsedTime: 3002
                error: time out
                status: false
  securitySchemes:
    x-api-key:
      name: API Key
      type: apiKey
      in: header
