openapi: 3.0.0
info:
  description: 'The update service allows to update the mirror data. This service queries unpaywall to get the snapshots and inserts their content in an elasticsearch index.'
  version: 1.0.0
  title: Update service
  contact:
    email: ezteam@couperin.org
    name: ezTeam
  license:
    name: CeCILL 2.1
    url: http://www.cecill.info/licences/Licence_CeCILL_V2.1-en.html
servers:
  - url: https://unpaywall.inist.fr/api
tags:
  - name: cron
  - name: job
  - name: ping
paths:
  /update:
    get:
      tags:
        - ping
      operationId: get-update
      summary: Name of service.
      description: Get name of update service.
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                response:
                  value:
                    message: update service
  
  /update/ping:
    get:
      operationId: get-update-ping
      summary: Ping update service.
      description: Ping update service.
      tags:
        - ping
      responses:
        '204':
          description: No Content
  
  /update/health:
    get:
      tags:
        - ping
      operationId: get-update-health
      summary: Health.
      description: Health on all service connected to update service.
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  redis:
                    type: object
                    properties:
                      elapsedTime:
                        type: integer
                      status:
                        type: boolean
                  elastic:
                    type: object
                    properties:
                      elapsedTime:
                        type: integer
                      status:
                        type: boolean
                  elapsedTime:
                    type: integer
                  status:
                    type: boolean
                x-examples:
                  Example 1:
                    redis:
                      elapsedTime: 1
                      status: true
                    elastic:
                      elapsedTime: 1
                      status: true
                    elapsedTime: 1
                    status: true
              examples:
                Success:
                  value:
                    redis:
                      elapsedTime: 1
                      status: true
                    elastic:
                      elapsedTime: 1
                      status: true
                    elapsedTime: 1
                    status: true
                Error redis:
                  value:
                    redis:
                      elapsedTime: 3001
                      status: false
                      error: time out
                    elastic:
                      elapsedTime: 1
                      status: true
                    elapsedTime: 3001
                    status: false
  
  /update/health/redis:
    get:
      tags:
        - ping
      operationId: get-update-health-redis
      summary: Health on redis service.
      description: Health on redis.
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Health'
  
  /update/health/elastic:
    get:
      tags:
        - ping
      operationId: get-update-health-elastic
      summary: Health on elastic service.
      description: Health on elastic.
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/Health'
  
  /update/job/snapshot:
    post:
      tags:
        - job
      operationId: post-update-job-snapshot
      summary: Start process download and insert snapshot from unpaywall.
      description: Download and insert the latest snapshot from unpaywall.org.
      security:
        - x-api-key: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - userName
              properties:
                interval:
                  type: string
        description: index where the unpaywall data will be inserted.
      responses:
        '202':
           $ref: '#/components/responses/Accepted'
        '401':
          $ref: '#/components/responses/Not-authorized'
        '409':
          $ref: '#/components/responses/Conflict'
  
  /update/job/download/insert/changefile/period:
    post:
      tags:
        - job
      operationId: post-update-job-period
      summary: Start process download and insert changefiles from unpaywall.
      description: Download and insert changefiles from unpaywall.org.
      security:
        - x-api-key: []
      requestBody:
        description: config for process
        content:
          application/json:
            schema:
              type: object
              required:
                - userName
              properties:
                index:
                  type: string
                interval:
                  type: string
                startDate:
                  type: string
                endDate:
                  type: string
                ignoreError:
                  type: boolean
                cleanFile:
                  type: boolean
      responses:
        '202':
          $ref: '#/components/responses/Accepted'
        '400':
          description: startDate cannot be in the futur or endDate cannot be lower than startDate.
        '401':
          $ref: '#/components/responses/Not-authorized'
        '409':
          $ref: '#/components/responses/Conflict'
  
  /update/job/insert/changefile/${filename}:
    post:
      tags:
        - job
      operationId: post-update-job-changefile-$-filename
      summary: Start process insert changesfiles downloaded on ezunpaywall.
      description: Insert changefiles already downloaded on ezunpaywall.
      security:
        - x-api-key: []
      parameters:
        - in: path
          name: filename
          description: filename
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                index:
                  type: string
                offset:
                  type: integer
                limit:
                  type: integer
                ignoreError:
                  type: boolean
                cleanFile:
                  type: boolean
        description: config for process
      responses:
        '202':
          $ref: '#/components/responses/Accepted'
        '400':
          description: startDate cannot be in the futur or endDate cannot be lower than startDate.
          content:
            application/json:
              examples:
                response:
                  value:
                    message: startDate cannot be in the futur or endDate cannot be lower than startDate.
        '401':
          $ref: '#/components/responses/Not-authorized'
        '404':
          $ref: '#/components/responses/File-not-found'
        '409':
          $ref: '#/components/responses/Conflict'
                
  /update/job/download/insert/history/period:
    post:
      tags:
        - job
      operationId: post-update-job-history
      summary: Start process download and insert changefiles from unpaywall and feed history.
      description: Download and insert changefiles from unpaywall.org and feed history.
      security:
        - x-api-key: []
      requestBody:
        description: config for process
        content:
          application/json:
            schema:
              type: object
              required:
                - userName
              properties:
                index:
                  type: string
                interval:
                  type: string
                startDate:
                  type: string
                endDate:
                  type: string
      responses:
        '202':
          $ref: '#/components/responses/Accepted'
        '400':
          description: startDate cannot be in the futur or endDate cannot be lower than startDate.
        '401':
          $ref: '#/components/responses/Not-authorized'
        '409':
          $ref: '#/components/responses/Conflict'
          
  /update/job/reset:
    post:
      tags:
        - job
      operationId: post-update-job-reset
      summary: Start process that roll back the current and the history index according to a date.
      description: roll back the current and the history index according to a date.
      security:
        - x-api-key: []
      requestBody:
        description: config for process
        content:
          application/json:
            schema:
              type: object
              required:
                - userName
              properties:
                index:
                  type: string
                startDate:
                  type: string
      responses:
        '202':
          $ref: '#/components/responses/Accepted'
        '400':
          description: startDate required
        '401':
          $ref: '#/components/responses/Not-authorized'
        '409':
          $ref: '#/components/responses/Conflict'
  
  /update/reports/${type}:
    get:
      tags:
        - job
      operationId: get-update-reports
      summary: Get reports.
      description: Get list of reports or latest report.
      parameters:
        - in: path
          name: type
          description: type of report (unpaywall or unpaywallHistory)
          required: true
          schema:
            type: string
        - in: query
          name: latest
          description: latest
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: report
          content:
            List of reports:
              examples:
                response:
                  value:
                    - 2022-10-10 13:10:51.json
                    - 2022-10-10 13:10:50.json
                    - 2022-10-10 13:10:49.json
                    - 2022-10-10 13:10:48.json
                    - 2022-10-10 13:10:47.json
                    - 2022-10-10 13:10:46.json
                    - 2022-10-10 13:10:45.json
                    - 2022-10-10 13:10:44.json
            Latest report:
              examples:
                response:
                  value:
                    done: true
                    createdAt: '2022-10-10T13:10:46.828Z'
                    endAt: '2022-10-10T13:10:47.084Z'
                    steps:
                      - task: getChangefiles
                        took: 0.002
                        status: success
                      - task: download
                        file: fake2.jsonl.gz
                        percent: 100
                        took: 0
                        status: success
                      - task: insert
                        index: unpaywall-test
                        file: fake2.jsonl.gz
                        linesRead: 100
                        addedDocs: 100
                        updatedDocs: 0
                        failedDocs: 0
                        percent: 100
                        took: 0.202
                        status: success
                    error: false
                    took: 0.256
  
  /update/reports/${type}/${filename}:
    get:
      tags:
        - job
      operationId: get-update-reports-$-filename
      summary: Get report.
      description: Get report with his filename.
      parameters:
        - in: path
          name: type
          description: type of report (unpaywall or unpaywallHistory)
          required: true
          schema:
            type: string
        - in: path
          name: filename
          description: filename
          required: true
          schema:
            type: string
      responses:
        '200':
          description: report
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    done: true
                    createdAt: '2022-10-10T13:10:46.828Z'
                    endAt: '2022-10-10T13:10:47.084Z'
                    steps:
                      - task: getChangefiles
                        took: 0.002
                        status: success
                      - task: download
                        file: fake2.jsonl.gz
                        percent: 100
                        took: 0
                        status: success
                      - task: insert
                        index: unpaywall-test
                        file: fake2.jsonl.gz
                        linesRead: 100
                        addedDocs: 100
                        updatedDocs: 0
                        failedDocs: 0
                        percent: 100
                        took: 0.202
                        status: success
                    error: false
                    took: 0.256
            Report:
              examples:
                response:
                  value:
                    done: true
                    createdAt: '2022-10-10T13:10:46.828Z'
                    endAt: '2022-10-10T13:10:47.084Z'
                    steps:
                      - task: getChangefiles
                        took: 0.002
                        status: success
                      - task: download
                        file: fake2.jsonl.gz
                        percent: 100
                        took: 0
                        status: success
                      - task: insert
                        index: unpaywall-test
                        file: fake2.jsonl.gz
                        linesRead: 100
                        addedDocs: 100
                        updatedDocs: 0
                        failedDocs: 0
                        percent: 100
                        took: 0.202
                        status: success
                    error: false
                    took: 0.256
        '404':
          $ref: '#/components/responses/File-not-found'
  
  /update/snapshots:
    get:
      tags:
        - job
      operationId: get-update-snapshots
      summary: Get snapshots.
      description: Get list of snapshot or latest snapshot.
      security:
        - x-api-key: []
      parameters:
        - in: query
          name: latest
          description: latest
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: snapshot
          content:
            Lists of snapshots:
              examples:
                response:
                  value:
                    - snapshot-2022-10-10.jsonl.gz
        '401':
          $ref: '#/components/responses/Not-authorized'

  /update/snapshots/${filename}:
    get:
      tags:
        - job
      operationId: get-update-snapshots-$-filename
      summary: Get snapshot.
      description: Get snapshot with his filename.
      security:
        - x-api-key: []
      parameters:
        - in: path
          name: filename
          description: filename
          required: true
          schema:
            type: string
      responses:
        '200':
          description: snapshot
        '401':
          $ref: '#/components/responses/Not-authorized'
        '404':
          $ref: '#/components/responses/File-not-found'
  
  /update/states:
    get:
      tags:
        - job
      operationId: get-update-states
      summary: Get state.
      description: Get latest state.
      responses:
        '200':
          description: state
          content:
            Latest state:
              examples:
                response:
                  value:
                    done: true
                    createdAt: '2022-10-10T13:10:51.417Z'
                    endAt: '2022-10-10T13:10:51.584Z'
                    steps:
                      - task: getChangefiles
                        took: 0.002
                        status: success
                      - task: insert
                        index: unpaywall-test
                        file: fake1.jsonl.gz
                        linesRead: 50
                        addedDocs: 50
                        updatedDocs: 0
                        failedDocs: 0
                        percent: 100
                        took: 0.165
                        status: success
                    error: false
                    took: 0.167
  
  /update/status:
    get:
      tags:
        - job
      summary: Get status
      operationId: get-update-status
      description: Get status
      responses:
        '200':
          description: status
          content:
            No process in progress:
              examples:
                response:
                  value: false
            Update in progress:
              examples:
                response:
                  value: true
  
  /update/unpaywall/changefiles:
    get:
      tags:
        - job
      operationId: get-update-unpaywall-changefiles
      summary: Get changefiles from unpaywall.
      description: Get changefiles from unpaywall.
      security:
        - x-api-key: []
      parameters:
        - in: query
          name: interval
          description: interval of changefiles ("week" or "day")
          required: false
          schema:
            type: string
      responses:
        '200':
          description: status
          content:
            List of daily changefiles of unpaywall:
              examples:
                response:
                  value:
                    - date: '2022-10-10T00:00:00.000Z'
                      filename: fake1.jsonl.gz
                      filetype: jsonl
                      last_modified: '2021-10-09T13:10:50.000Z'
                      lines: 50
                      size: 19896
                      url: http://fakeUnpaywall:3000/daily-feed/changefiles/fake1.jsonl.gz
                    - date: '2022-10-09T00:00:00.000Z'
                      filename: fake2.jsonl.gz
                      filetype: jsonl
                      last_modified: '2022-10-09T13:10:50.000Z'
                      lines: 100
                      size: 44137
                      url: http://fakeUnpaywall:3000/daily-feed/changefiles/fake2.jsonl.gz
                    - date: '2022-10-08T00:00:00.000Z'
                      filename: fake3.jsonl.gz
                      filetype: jsonl
                      last_modified: '2022-10-08T13:10:50.000Z'
                      lines: 2000
                      size: 877494
                      url: http://fakeUnpaywall:3000/daily-feed/changefiles/fake3.jsonl.gz
            List of weekly changefiles of unpaywall:
              examples:
                response:
                  value:
                    - date: '2022-10-10T00:00:00.000Z'
                      filename: fake1.jsonl.gz
                      filetype: jsonl
                      last_modified: '2021-10-09T13:10:50.000Z'
                      lines: 50
                      size: 19896
                      url: http://fakeUnpaywall:3000/feed/changefiles/fake1.jsonl.gz
                    - date: '2022-10-09T00:00:00.000Z'
                      filename: fake2.jsonl.gz
                      filetype: jsonl
                      last_modified: '2022-10-09T13:10:50.000Z'
                      lines: 100
                      size: 44137
                      url: http://fakeUnpaywall:3000/feed/changefiles/fake2.jsonl.gz
                    - date: '2022-10-08T00:00:00.000Z'
                      filename: fake3.jsonl.gz
                      filetype: jsonl
                      last_modified: '2022-10-08T13:10:50.000Z'
                      lines: 2000
                      size: 877494
                      url: http://fakeUnpaywall:3000/feed/changefiles/fake3.jsonl.gz
        '401':
          $ref: '#/components/responses/Not-authorized'
  
  /update/cron/${type}/start:
    post:
      tags:
        - cron
      operationId: post-cron-start
      summary: Start cron.
      description: Start update cron.
      security:
        - x-api-key: []
      parameters:
        - in: path
          name: type
          description: type of report (unpaywall or unpaywallHistory)
          required: true
          schema:
            type: string
      responses:
        '202':
          $ref: '#/components/responses/Accepted'
        '401':
          $ref: '#/components/responses/Not-authorized'
      
      
      
  /update/cron/${type}/stop:
    post:
      tags:
        - cron
      operationId: post-cron-stop
      description: Stop cron.
      summary: Stop cron.
      security:
        - x-api-key: []
      parameters:
        - in: path
          name: type
          description: type of report (unpaywall or unpaywallHistory)
          required: true
          schema:
            type: string
      responses:
        '202':
          $ref: '#/components/responses/Accepted'
        '401':
          $ref: '#/components/responses/Not-authorized'
      
  /update/cron/${type}:
    patch:
      tags:
        - cron
      operationId: patch-cron
      summary: update cron.
      description: update cron.
      security:
        - x-api-key: []
      parameters:
        - in: path
          name: type
          description: type of report (unpaywall or unpaywallHistory)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  config:
                    type: object
                    properties:
                      time:
                        type: string
                      status:
                        type: boolean
                      index:
                        type: string
                      interval:
                        type: string
                x-examples:
                  example-1:
                    config:
                      time: '* * * * * *'
                      status: false
                      index: unpaywall
                      interval: day
              examples:
                updated:
                  value:
                    config:
                      time: '* 30 12-15 * * *'
                      status: true
                      index: unpaywall
                      interval: day
        '401':
          $ref: '#/components/responses/Not-authorized'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                time:
                  type: string
                index:
                  type: string
                interval:
                  type: string
              x-examples:
                example-1:
                  time: ''
                  index: ''
                  interval: ''
            examples:
              daily:
                value:
                  time: 0 0 0 * * *
                  index: unpaywall
                  interval: day
              weekly:
                value:
                  time: 0 0 0 * * 0
                  index: unpaywall
                  interval: weekly
  
    get:
      tags:
        - cron
      operationId: get-cron
      summary: Get config of cron.
      description: Get config of cron.
      parameters:
        - in: path
          name: type
          description: type of report (unpaywall or unpaywallHistory)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  config:
                    type: object
                    properties:
                      time:
                        type: string
                      status:
                        type: boolean
                      index:
                        type: string
                      interval:
                        type: string
                x-examples:
                  example-1:
                    config:
                      time: '* * * * * *'
                      status: false
                      index: unpaywall
                      interval: day
              examples:
                day:
                  value:
                    config:
                      time: 0 0 0 * * *
                      status: true
                      index: unpaywall
                      interval: day
                week:
                  value:
                    config:
                      time: 0 0 0 * * *
                      status: true
                      index: unpaywall
                      interval: day
                off:
                  value:
                    config:
                      time: 0 0 0 * * *
                      status: false
                      index: unpaywall
                      interval: day

components:
  responses:
    Accepted:
      description: Accepted
      headers: {}
    Not-authorized:
      description: Not authorized
      headers: {}
      content:
        application/json:
          examples:
            response:
              value:
                message: Not authorized
    Conflict:
      description: Conflict
      headers: {}
      content:
        application/json:
          examples:
            response:
              value:
                message: Update in progress.
    File-not-found:
      description: File not found
      headers: {}
      content:
        application/json:
          examples:
            response:
              value:
                message: File not found.
    Health:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              status:
                type: boolean
              elapsedTime:
                type: integer
            x-examples:
              Example 1:
                name: redis
                status: true
                elapsedTime: 1
          examples:
            Success:
              value:
                name: name of service
                status: true
                elapsedTime: 1
            Error redis:
              value:
                name: redis
                elapsedTime: 3002
                error: time out
                status: false
  securitySchemes:
    x-api-key:
      type: apiKey
      in: header
      name: API Key
  schemas: {}
